version: 1
formatters:
  basic:
    format: '[%(levelname)s] %(message)s'
  simple:
    format: '%(asctime)s %(name)s -- [%(levelname)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: basic
    stream: ext://sys.stdout

loggers:
  awsLogger:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]